[package]
authors = ["Jamie Blondin <jblondin@gmail.com>"]
categories = ["parser-implementations"]
description = "A CSV file format sniffer for Rust"
edition = "2021"
exclude = ["tests/data/*"]
keywords = ["csv"]
license = "MIT"
name = "csv-sniffer"
repository = "https://github.com/jblondin/csv-sniffer"
version = "0.3.1"

[dependencies]
bitflags = "1"
csv = "1"
csv-core = "0.1"
memchr = "2"
regex = "1.5"
