[package]
name = "csv-sniffer"
description = "A CSV file format sniffer for Rust"
version = "0.1.1"
authors = ["Jamie Blondin <jblondin@gmail.com>"]
license-file = "LICENSE"
repository = "https://github.com/jblondin/csv-sniffer"
exclude = ["tests/data/*"]

[dependencies]
csv-core = "0.1"
csv = "1"
regex = "1.5"
bitflags = "1"
memchr = "2"
