[package]
authors = ["Jamie Blondin <jblondin@gmail.com>"]
description = "A CSV file format sniffer for Rust"
exclude = ["tests/data/*"]
license-file = "LICENSE"
name = "csv-sniffer"
repository = "https://github.com/jblondin/csv-sniffer"
version = "0.3.0"

[dependencies]
bitflags = "1"
csv = "1"
csv-core = "0.1"
memchr = "2"
regex = "1.5"
